task/urls.py
"""
task URL Configuration
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app import views
from rest_framework import routers

# routers API REST
router = routers.DefaultRouter()
router.register(r'task-form-field', views.TaskFormFieldsViewSet)


urlpatterns = [
    re_path(r'^', include('user_profile.urls')),
    re_path(r'^', include('messages.urls')),
    re_path(r'^', include('store.urls')),
    re_path(r'^', include('project.urls')),
    re_path(r'^', include('audits.urls')),
    # Administrador
    path('administrator/', admin.site.urls),
    path('administrator/doc/', include('django.contrib.admindocs.urls')),
    # Dashboard
    path('', views.dashboard, name='dashboard'),
    # Auditor
    re_path(
        r'update-rating-task/(?P<pk>\d+)/$',
        views.UpdateRatingTaskView.as_view(),
        name='update-rating-task',
    ),
    re_path(
        r'new-rate-task/(?P<pk>\d+)/$',
        views.CreateRatingTaskView.as_view(),
        name='create-rating-task',
    ),
    # Operator
    path(
        'calendar-operator',
        views.calendar_operator,
        name='calendar-operator'
    ),
    re_path(
        r'task-execute-new-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorNew.as_view(),
        name='task-execute-doc-new'
    ),
    re_path(
        r'task-execute-update-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorUpdate.as_view(),
        name='task-execute-doc-update'
    ),
    re_path(
        r'task-administrator-remove/(?P<pk>\d+)/$',
        views.TaskDelete.as_view(),
        name='task-delete'
    ),
    re_path(
        r'task-execute-new-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorNew.as_view(),
        name='task-execute-form-new'
    ),
    re_path(
        r'task-execute-update-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorUpdate.as_view(),
        name='task-execute-form-update'
    ),
    # Administrador
    path(
        'reports-administrator/',
        views.reports_administrator,
        name='reports_administrator'
    ),
    path(
        'help-administrator/',
        views.Help.as_view(),
        name='help-administrator'
    ),
    path(
        'help-operator/',
        views.HelpOperator.as_view(),
        name='help-operator'
    ),
    re_path(
        r'task-administrator/',
        views.task_administrator,
        name='task_administrator'
    ),
    re_path(
        r'assign-task/(?P<pk>\d+)/$',
        views.AssignTask.as_view(),
        name='task_assign'
    ),
    re_path(
        r'task-administrator-update/(?P<pk>\d+)/$',
        views.TaskAdministratorUpdateDoc.as_view(),
        name='task_administrator_update_document'
    ),
    re_path(
        r'task-administrator-update-modal',
        views.TaskAdministratorUpdateDocModal.as_view(),
        name='task_administrator_update_document_modal'
    ),
    re_path(
        r'task-administrator-new-document/',
        views.TaskAdministratorNewDoc.as_view(),
        name='task_administrator_new_document'
    ),
    re_path(r'^task-execute/(?P<store_id>\d+|)/(?P<task_id>\d+|)/(?P<project_id>\d+|)', views.StoreTaskExecute.as_view()),
    path('task-upload-evidence/', views.upload_task_evidence),
    path('task-audit/<int:result_id>', views.TaskAudit.as_view()),
    path('login/', auth_views.login, {'template_name': 'site/login.html'}),
    path('/', auth_views.login, {'template_name': 'site/login.html'}),
    path('forgot-password/', auth_views.password_reset, {'template_name': 'site/forgot_password.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, {'template_name': 'site/password_reset_done.html'}, name='password_reset_done'),
    path('logout/', views.log_out, name='logout'),
    # API REST
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

messages/models.py
from django.db import models
from task.middlewares import RequestMiddleware
from datetime import datetime


MESSAGE_TYPE_CHOICES = (
    ('Message', 'Message'),
    ('Request', 'Request'),
)

class MessageAttach(models.Model):
    name = models.ImageField(blank=True, upload_to='static/files/messages/')
    message = models.ForeignKey('Message',  on_delete="cascade", related_name="attachments")


class Message(models.Model):
    """ Model Messages :Message and Request """
    subject         = models.CharField(max_length=100, blank=False, null=False, verbose_name="Asunto",)
    text            = models.TextField(blank=True, verbose_name="Mensaje",)
    type            = models.CharField(max_length=30, choices = MESSAGE_TYPE_CHOICES)
    to_user         = models.ForeignKey('user_profile.User', on_delete=models.CASCADE,null=True, related_name='me_to', verbose_name="Enviar a",)
    from_user       = models.ForeignKey('user_profile.User', on_delete=models.CASCADE,null=True, related_name='me_from',)
    date            = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    read            = models.BooleanField(default=False)
    task_assignment = models.ForeignKey('app.TaskAssignment', on_delete=models.CASCADE,null=True, blank=True, related_name='me_from',verbose_name="Referente a tarea",)
    reply_to = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        db_table = 'message'

    def get_date(self):
        today = datetime.now()
        if today.day==self.date.day:
            return "%s:%s" % (self.date.hour, self.date.minute)
        else:
            return self.date

    def is_own(self):
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request
        return self.to_user == request.user

    def __str__(self):
        return "%s" % (self.subject)

templates/operator/calendar.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Actualizar tarea{% endblock %}
{% block css  %}
    <link href="/static/assets/node_modules/calendar/dist/fullcalendar.css" rel="stylesheet">
{% endblock %}
{% block contentHeader %}
<div class="row page-titles">
    <div class="col-md-5 align-self-center">
        <h4 class="text-themecolor">Calendario</h4>
    </div>
</div>
{% endblock %}
{% block content %}
<div class="container-fluid">
<div class="row">
    <div class="col-md-12">
        <div class="calendar" id="calendar"></div>
    </div>
</div>

</div>



{% endblock %}


{% block javascript %}
<script src="/static/assets/js/pages/jasny-bootstrap.js"></script>
<script src="/static/assets/node_modules/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
<script src="/static/assets/node_modules/calendar/jquery-ui.min.js"></script>
<script src="/static/assets/node_modules/moment/moment.js"></script>

<script src="/static/assets/js/fullcalendar.min.js"></script>
<script src="/static/assets/js/locale-all.js"></script>
<script>
var today = new Date($.now());
var defaultEvents = JSON.parse('{{ task|safe }}');
console.log(defaultEvents);

var $calendar = $('#calendar');

$calendar.fullCalendar({
    header: {
        left: 'today',
        center: 'title',
        right: 'prev,next'
    },
    locale: 'es',
    eventLimit: true,
    events: defaultEvents,
});
</script>
{% endblock %}

templates/operator/task_execute_document.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Register Task{% endblock %}

{% block contentHeader %}
<div class="container-fluid">
   <!-- <div class="alert alert-danger">
        {{ form.errors }}
    </div>
-->
        <div class="row">
        <div class="col-12">

<div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Tarea: {{ ta.task.name }}</h4>
                    </div>
                    
</div>


<div class="row"  style="padding: 0">
        <div class="col">
    
                <div class="p-t-0" >
                    <div class=" b-all shadow-none">


        <div class="card border-dark">
            <div class="card-body">
                {% if new %}
                    {% include "dashboard/report_problem.html" %}
                {% endif %}
                <form method="post" class="form-horizontal" enctype="multipart/form-data">
                   {% csrf_token %}
                   <br>
                   <p class="text-justify">

                    <div class="row">
                        <div class="col-6">
                            <i class="ti-alarm-clock"></i> Hora de inicio:  {{  ta.task.start_hour }}
                        </div>
                        <div class="col-6">
                            <i class="ti-alarm-clock"></i> Hora de finalización:  {{  ta.task.end_hour }}
                        </div>                                                                          
                    </div>
                    <br>
                    <b>Instrucciones:</b><br>
                    {% firstof ta.task.instructions|safe 'Sin descripción' %}
                </p>
                <br>
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item"> 
                       <a class="nav-link active show" data-toggle="tab" href="#file1" role="tab" aria-selected="true"><span class="hidden-sm-up"><i class="ti-file"></i></span> <span class="hidden-xs-down">Archivo 1</span>
                       </a> 
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" data-toggle="tab" href="#file2" role="tab" aria-selected="false"><span class="hidden-sm-up"><i class="ti-file"></i></span> <span class="hidden-xs-down">Archivo 2</span></a> 
                   </li>
                   <li class="nav-item"> 
                       <a class="nav-link" data-toggle="tab" href="#file3" role="tab" aria-selected="false"><span class="hidden-sm-up"><i class="ti-file"></i></span> <span class="hidden-xs-down">Archivo 3</span>
                       </a> 
                   </li>
               </ul>
               <!-- Tab panes -->
               <div class="tab-content tabcontent-border">
                <div class="tab-pane p-20 active show" id="file1" role="tabpanel">

                    {% if upload_one_ft == 'image'  %}
                 
                        <input class="dropify-es" name="upload_one" id="id_upload_one"  type="file" data-default-file="/{{ form.upload_one.value }}">
                      
                    {% endif %}
                    {% if upload_one_ft == 'doc'  %}
                    {% if form.upload_one.value  %}
                    <h3 class="card-title text-center"><a href="/{{ form.upload_one.value }}" target="_blank" ><i class="ti-download" ></i> Download  </a></h3>

                    <h6 class="card-title text-center">Subir un nuevo Documento/Imagen</h6>
                    {% endif %}
                        <input type="file" name="upload_one" class="dropify-es" id="input-file-max-fs" type="file" data-max-file-size="2M">

                    {% endif %}
                </div>


                <div class="tab-pane p-20" id="file2" role="tabpanel">
                    {% if upload_two_ft == 'image'  %}
                   
                        <input class="dropify-es" name="upload_two" id="id_upload_two"  type="file" data-default-file="/{{ form.upload_two.value }}">
                    
                    {% endif %}
                    {% if upload_two_ft == 'doc'  %}
                    {% if form.upload_two.value  %}
                    <h3 class="card-title text-center"><a href="/{{ form.upload_two.value }}" target="_blank" ><i class="ti-download" ></i> Download  </a></h3>

                    <h6 class="card-title text-center">Upload new Document/Photo</h6>
                    {% endif %}
                    <input type="file" name="upload_two" class="dropify-es" id="input-file-max-fs" type="file" data-max-file-size="2M">
                    {% endif %}

                </div>
                <div class="tab-pane p-20" id="file3" role="tabpanel">
                    {% if upload_three_ft == 'image'  %}
                        <input class="dropify-es" name="upload_three" id="id_upload_three"  type="file" data-default-file="/{{ form.upload_three.value }}">
                    {% endif %}
                    {% if upload_three_ft == 'doc'  %}
                    {% if form.upload_three.value  %}
                    <h3 class="card-title text-center"><a href="/{{ form.upload_three.value }}" target="_blank" ><i class="ti-download" ></i> Download  </a></h3>

                    <h6 class="card-title text-center">Upload new Document/Photo</h6>
                    {% endif %}
                    <input type="file" name="upload_three" class="dropify-es" id="input-file-max-fs" type="file" data-max-file-size="2M">
                    {% endif %}
                </div>
           </div>

           <button type="submit"  class="btn btn-primary btn-block btn-lg" >GUARDAR</button>
           <input type="hidden" name="task_assignment" id="id_task_assignment" value="{{ ta.id }}" >
       </form>

   </div>
</div>
</div>

</div>
</div>
</div>


        </div>

    </div>

</div>

{% endblock %}

{% block contentContainer %}

{% endblock %}

{% block javascript %}
<script src="/static/assets/js/pages/jasny-bootstrap.js"></script>
<script src="/static/assets/node_modules/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
<script src="/static/assets/node_modules/dropify/dist/js/dropify.min.js"></script>
<script>
    $(document).ready(function(){
        $("input").addClass("form-control");
        $("select").addClass("form-control");
        $("textarea").addClass("form-control");
        $("select").select2();
        document.getElementsByTagName("form")[0].setAttribute("enctype", "multipart/form-data");

        
    });

$(document).ready(function() {


    // Translated
    $('.dropify-es').dropify({
        messages: {
            default: 'Arrastra un archivo aquí o da click',
            replace: 'Arrastra un archivo para reemplazarlo',
            remove: 'Eliminar',
            error: 'Error, intentalo nuevamente'
        }
    });

});
</script>
{% endblock %}

templates/operator/task_execute_form.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Register Task{% endblock %}

{% block content %}

<div class="row" id="app">
  {{ form.errors }}
  <div class="col-md-3 col-sm-12"> </div>
  <div class="col-md-6 col-sm-12">
    {% include "dashboard/report_problem.html" %}
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h4 class="m-b-0 text-white">{{ ta.task.name }}</h4>
      </div>
      <div class="card-body">
        <div class="card-text">
          <form method="post">
            {% csrf_token %}
            <div id="more">
              <div class="row">
                <div class="col-md-6 text-truncate">
                  <i class="ti-stats-up"></i> % Completo: {{ ta.task.get_complete_percent }}
                </div>
                <div class="col-md-6 text-truncate">
                  <i class="ti-alarm-clock"></i> Duración: {{ ta.task.get_duration }}
                </div>
                <div class="col-md-6 text-truncate">
                  <i class="ti-alarm-clock"></i> Hora inicio: {{ ta.task.start_hour }}
                </div>
                <div class="col-md-6 text-truncate">
                  <i class="ti-alarm-clock"></i> Hora finalización: {{ ta.task.end_hour }}
                </div>
              </div>
            </div>
            <hr>
            {% csrf_token %}
            {% for f in fields %}
            <div class="form-group">
              <label>{{f.label}}</label>
              <div>
                {% if not f.is_multiple %}
                {% if f.input_type == 'textarea' %}
                <textarea rows="6" class="form-control" required name="{{f.id}}" v-bind:value="values[{{f.id}}]"
                  placeholder="response"></textarea>
                {% else %}
                <input class="form-control" required name="{{f.id}}" v-bind:value="values[{{f.id}}]" placeholder="response" />
                {% endif %}
                {% else %}
                {% for option in f.options_array %}
                <div class="form-check" style="display: flex; align-items: center">
                  <input required style="width: 1.2em; margin-right: 1em" type="radio" name={{f.id}} id="radio_{{option}}"
                    value="{{option}}" :checked="values[{{f.id}}] == '{{option}}'">
                  <label class="form-check-label" for="radio_{{option}}">{{option}}</label>
                </div>
                {% endfor %}
                {% endif %}
              </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary mb-12 mt-3">GUARDAR</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3 col-sm-12"> </div>
</div>
{% endblock %}

{% block javascript %}
<script src="/static/assets/js/pages/jasny-bootstrap.js"></script>
<script src="/static/assets/node_modules/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
<script>
  $(document).ready(function () {
    $("input").addClass("form-control");
    $("select").addClass("form-control");
    $("textarea").addClass("form-control");
    $("select").select2();
    document.getElementsByTagName("form")[0].setAttribute("enctype", "multipart/form-data");
  });

</script>
<script>
  try {
    var responses = JSON.parse('{{responses|safe}}');
  } catch (ex) {
    var responses = {};
  }
  var app = new Vue({
    el: '#app',
    data: {
      values: {
        ...responses
      },
    }
  })
</script>
{% endblock %}