task/urls.py
"""
task URL Configuration
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app import views
from rest_framework import routers

# routers API REST
router = routers.DefaultRouter()
router.register(r'task-form-field', views.TaskFormFieldsViewSet)


urlpatterns = [
    re_path(r'^', include('user_profile.urls')),
    re_path(r'^', include('messages.urls')),
    re_path(r'^', include('store.urls')),
    re_path(r'^', include('project.urls')),
    re_path(r'^', include('audits.urls')),
    # Administrador
    path('administrator/', admin.site.urls),
    path('administrator/doc/', include('django.contrib.admindocs.urls')),
    # Dashboard
    path('', views.dashboard, name='dashboard'),
    # Auditor
    re_path(
        r'update-rating-task/(?P<pk>\d+)/$',
        views.UpdateRatingTaskView.as_view(),
        name='update-rating-task',
    ),
    re_path(
        r'new-rate-task/(?P<pk>\d+)/$',
        views.CreateRatingTaskView.as_view(),
        name='create-rating-task',
    ),
    # Operator
    path(
        'calendar-operator',
        views.calendar_operator,
        name='calendar-operator'
    ),
    re_path(
        r'task-execute-new-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorNew.as_view(),
        name='task-execute-doc-new'
    ),
    re_path(
        r'task-execute-update-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorUpdate.as_view(),
        name='task-execute-doc-update'
    ),
    re_path(
        r'task-administrator-remove/(?P<pk>\d+)/$',
        views.TaskDelete.as_view(),
        name='task-delete'
    ),
    re_path(
        r'task-execute-new-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorNew.as_view(),
        name='task-execute-form-new'
    ),
    re_path(
        r'task-execute-update-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorUpdate.as_view(),
        name='task-execute-form-update'
    ),
    # Administrador
    path(
        'reports-administrator/',
        views.reports_administrator,
        name='reports_administrator'
    ),
    path(
        'help-administrator/',
        views.Help.as_view(),
        name='help-administrator'
    ),
    path(
        'help-operator/',
        views.HelpOperator.as_view(),
        name='help-operator'
    ),
    re_path(
        r'task-administrator/',
        views.task_administrator,
        name='task_administrator'
    ),
    re_path(
        r'assign-task/(?P<pk>\d+)/$',
        views.AssignTask.as_view(),
        name='task_assign'
    ),
    re_path(
        r'task-administrator-update/(?P<pk>\d+)/$',
        views.TaskAdministratorUpdateDoc.as_view(),
        name='task_administrator_update_document'
    ),
    re_path(
        r'task-administrator-update-modal',
        views.TaskAdministratorUpdateDocModal.as_view(),
        name='task_administrator_update_document_modal'
    ),
    re_path(
        r'task-administrator-new-document/',
        views.TaskAdministratorNewDoc.as_view(),
        name='task_administrator_new_document'
    ),
    re_path(r'^task-execute/(?P<store_id>\d+|)/(?P<task_id>\d+|)/(?P<project_id>\d+|)', views.StoreTaskExecute.as_view()),
    path('task-upload-evidence/', views.upload_task_evidence),
    path('task-audit/<int:result_id>', views.TaskAudit.as_view()),
    path('login/', auth_views.login, {'template_name': 'site/login.html'}),
    path('/', auth_views.login, {'template_name': 'site/login.html'}),
    path('forgot-password/', auth_views.password_reset, {'template_name': 'site/forgot_password.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, {'template_name': 'site/password_reset_done.html'}, name='password_reset_done'),
    path('logout/', views.log_out, name='logout'),
    # API REST
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.contrib.gis.db import models
from functools import reduce
from datetime import datetime, date
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext
from task.middlewares import RequestMiddleware
from datetime import datetime

TASK_TYPE_CHOICES = (
    ('document', 'Foto / Documento'),
    ('form', 'Formulario / Encuesta'),
)

TASK_PERIODICITY_CHOICES = (
    ('Daily', 'Diario'),
    ('Monthly', 'Mensual'),
    ('Unique', 'Único'),
)

TASK_DAY_NUMBER_CHOICES = (
    ('01', '01'),
    ('02', '02'),
    ('03', '03'),
    ('04', '04'),
    ('05', '05'),
    ('06', '06'),
    ('07', '07'),
    ('08', '08'),
    ('09', '09'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
    ('End of the month', 'End of the month'),
)

FORM_TYPE_CHOICES = (
    ('checkbox', 'Checkbox'),
    ('number', 'Número'),
    ('textarea', 'Texto largo'),
    ('radio', 'Selección múltiple'),
)

FORM_CLASS_CHOICES = (
    ('form-control', 'Normal'),
)

TASK_FORM_INPUT_TYPES = (
    ('open-ended-question', 'Open ended question'),
    ('multiple-choice', 'Multiple choise'),
    ('checkbox', 'checkbox'),
    ('number', 'number'),
)


class TaskStore(models.Model):
    store = models.ForeignKey('store.Store', on_delete=models.CASCADE)
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    

class Task(models.Model):
    """ Model task """
    name = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        default=None,
        verbose_name="Nombre"
    )
    owner = models.ForeignKey(
        'user_profile.User',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Creado por"
    )
    periodicity = models.CharField(
        max_length=30,
        choices=TASK_PERIODICITY_CHOICES,
        verbose_name="Periodicidad"
    )
    type = models.CharField(max_length=30, choices=TASK_TYPE_CHOICES, verbose_name="Tipo de tarea",)
    # aplica para todos los tipo de periodicidad
    start_date = models.DateField(
        blank=True,
        null=True,
        verbose_name="Fecha de inicio"
    )
    end_date = models.DateField(
        blank=True,
        null=True,
        verbose_name="Fecha de finalización"
    )
    start_hour = models.TimeField(
        null=True,
        blank=True,
        default=None,
        verbose_name="Hora de inicio"
    )
    end_hour = models.TimeField(
        null=True,
        blank=True,
        default=None,
        verbose_name="Hora de finalización"
    )
    # Dias de la semana en la que se ejecuta una tarea empieza en lunes=0 y
    # esta separada por ","
    days = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default="0,1,2,3,4,5,6",
        verbose_name="Días"
    )
    week = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default="0,1,2,3",
        verbose_name="Semana"
    )
    # datos para tipo Monthly
    day_number = models.CharField(
        max_length=30,
        choices=TASK_DAY_NUMBER_CHOICES,
        null=True,
        verbose_name="Día",
        blank=True
    )
    active = models.BooleanField(
        default=True
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Ejecutar después de",
        blank=True,
        related_name='ta_task'
    )
    store = models.ManyToManyField(
        'store.Store',
        null=True,
        blank=True,
        verbose_name="Tienda",
        related_name='tasks'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    instructions = models.TextField(blank=True, verbose_name="Instrucciones",)
    is_audit = models.BooleanField(default=False)
    
    def get_periodicity(self):
        return dict(TASK_PERIODICITY_CHOICES)[self.periodicity]
    
    def get_type(self):
        return dict(TASK_TYPE_CHOICES)[self.type] 
    
    def verbose_type(self):
        return dict(TASK_TYPE_CHOICES)[self.type] 

    def get_complete_percent(self):
        return '{}%'.format(int((self.get_total_completed_tasks() * 100) / self.get_total_tasks()))

    def get_score(self):
        childrens = self.ta_task.all()
        completed_tasks = 0
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request

        for children in childrens:
            if (children.is_complete(request)):
                completed_tasks += 1

        if completed_tasks == 0:
            return 0
        completed = int((completed_tasks * 100) / childrens.count())
        return '{}%'.format(completed)

    def projects_names(self):
        names = []
        return reduce(
            lambda prev, ta: "{}, {}".format(prev, ta.project.name) if prev else ta.project.name, 
            self.assignment.all(),
            ''
        )

    def get_duration(self):
        return (
            datetime.combine(date.today(), self.end_hour) -
            datetime.combine(date.today(), self.start_hour)
        )

    def get_instructions(self):
        if len(self.instructions) > 50:
            return self.instructions[:50] + "..."
        else:
            return self.instructions[:50]

    def is_complete(self):
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request
        return TaskAssignmentResult.objects.filter(
            task=self,
            store__manager=request.user
        ).exists()

    def get_total_tasks(self, count=1):
        if not self.ta_task:
            return count
        return reduce((lambda x, y: x + y.get_total_tasks()), self.ta_task.all(), count)

    def get_total_completed_tasks(self, count=None):
        if not self.ta_task:
            return count
        if count is None:
            count = 1 if self.is_complete() else 0

        return reduce(
            (lambda x, y: x + y.get_total_completed_tasks()),
            self.ta_task.all(),
            count
        )

    def get_progress(self):
        completed = self.get_total_completed_tasks()
        if (completed == 0):
            return 0
        total_tasks = self.get_total_tasks()

        return int((completed * 100) / total_tasks)

    class Meta:
        db_table = 'task'

    def __str__(self):
        return self.name


class TaskFormFields(models.Model):
    label = models.CharField(max_length=200)
    input_type = models.CharField(
        max_length=200,
        choices=TASK_FORM_INPUT_TYPES
    )
    options = models.TextField(blank=True)
    task = models.ForeignKey(
        to=Task,
        on_delete=models.CASCADE,
        related_name='formFields'
    )
    optional = models.BooleanField(default=False)

    def is_multiple(self):
        return self.input_type == 'multiple-choice'

    def options_array(self):
        return self.options.split(',')


class TaskFormResponse(models.Model):
    assignment_result = models.ForeignKey(
        to='TaskAssignmentResult',
        on_delete=models.CASCADE,
        related_name="form_responses"
    )
    formField = models.ForeignKey(
        to='TaskFormFields',
        on_delete=models.CASCADE
    )
    response = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)


# Asignación de tareas a proyectos
class TaskAssignment(models.Model):
    """ Model Task Form Template: save json form """
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE,
        null=True,
        related_name='assignment'
    )
    project = models.ForeignKey(
        'project.Project',
        on_delete=models.CASCADE,
        null=True,
        related_name='task_assignments'
    )

    class Meta:
        db_table = 'task_assignment'

    def __str__(self):
        try:
            return "%s (%s)" % (self.task.name, self.store.name)
        except(ObjectDoesNotExist, AttributeError):
            return ''

    def is_saved(self, date):
        try:
            r = TaskAssignmentResult.objects.filter(
                #task_assignment=self,
                date__day=date.day,
                date__month=date.month,
                date__year=date.year
            )[:1].get()
            return {'object': r, 'status': True}
        except TaskAssignmentResult.DoesNotExist:
            return {'object': None, 'status': False}
    
    def next_task_assignment(self):
        next_assignment = TaskAssignment.objects.filter(
            task__seguimiento__tarea_completada=0,
            project=self.project,
            task__parent=self.task,
        ).first()
        if (next_assignment):
            return next_assignment

    def is_auditee(self, date):
        try:
            r = TaskAssignmentResult.objects.filter(
                task_assignment=self,
                date__day=date.day,
                date__month=date.month,
                date__year=date.year
            )[:1].get()
            return {'object': r, 'status': True}
        except TaskAssignmentResult.DoesNotExist:
            return {'object': None, 'status': False}


class SeguimientoTareas(models.Model):
    tarea = models.CharField(max_length=50),
    task = models.ForeignKey(Task, related_name="seguimiento", on_delete=models.DO_NOTHING)
    tarea_completada = models.BooleanField()
    nombre_tienda = models.CharField(max_length=50)

    class Meta:
        db_table = 'seguimiento_tareas'
        managed = False

    def delete(self, *args, **kwargs):
        pass # deletion of a view row is never valid

class AvancesProyectoView(models.Model):

templates/auditor/audit-reports.html
{% extends 'site/base_dashboard.html' %}
{% block content %}
    <div class="embed-responsive embed-responsive-21by9">
        <iframe src="http://axdigital.co:3000/public/dashboard/22ee10b1-9d3e-4a20-b40d-b43a69f5927f" frameborder="0" allowtransparency></iframe>
    </div>
{% endblock %}

templates/auditor/audit_list.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Dashboard{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<div class="card-body" >

<div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h3 class="text-themecolor">Visitas Agendadas</h3>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <a href="{% url 'create-audit' %}">
                               <button type="button" class="btn btn-info  d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> AGENDAR VISITA</button>
                            </a>
                            <a href="{% url 'edit-audit-form' 1 %}">
                                <button type="button" class="btn btn-info  d-lg-block m-l-15"><i class="fa fa-plus-circle"></i> ACTUALIZAR FORMULARIO</button>
                            </a>
                        </div>
                </div>
</div>
   <hr class="m-t-0 m-b-40">

    <div class="card shadow-none">
        <div>
           
            <table class="display nowrap table table-hover table-striped table-bordered dataTable no-footer dtr-inline" id="table">
                <thead >
                    <tr>
                        <th >Nombre de tienda:</th>
                        <th>Fecha de la visita</th>
                        <th>Resultado</th>
                      <th  class="text-center">Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pv in object_list %}
                    <tr>
                        <td>{{ pv.store.name }}</td>
                        <td>{{ pv.date_time_programmed }}</td>
                        {% if pv.audit_result.all.count == 0 %}
                            <td><a class="btn btn-sm btn-primary" href="{% url 'run-visit' pv.id %}">EJECUTAR VISITA</a></td>
                        {% else %}
                            <td><div>{{ pv.calculate_audit_result }}% Cumplido</div></td>
                        {% endif %}
                        <td class="text-center">  
                        {% if pv.audit_result.all.count == 0 %}
                        {% else %}                                              
                            <a href="/edit-audit/{{pv.id}}" data-toggle="tooltip" data-original-title="Edit"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                        {% endif %}
                            <!-- <a href="javascript:void(0)" data-toggle="tooltip" data-original-title="Close"> <i class="fa fa-close text-danger"></i> </a> -->
                             </td>
                    </tr>
                    {% empty %}
                    <td>Aún no existen resultados</td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

{% block javascript %}



<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
<script src="/static/assets/node_modules/sparkline/jquery.sparkline.min.js"></script>

<script>
    $(document).ready(function() {

$('#table').DataTable({
                dom: 'Bfrtip',
                bLengthChange: true,
                buttons: [
                'copy', 'excel', 'pdf', 'print'
                ],
                responsive: true, 
                order: [[ 1, "desc" ]],
            	"displayLength": 20,
                language: {
                    "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Spanish.json"
                    },
            });
  })

    
</script>

{% endblock %}

templates/auditor/create-audit.html
{% extends 'site/base_dashboard.html' %}
{% load widget_tweaks %}
{% block contentHeader %}
<div class="container-fluid">
<div class="row">
<div class="col-12">

<div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Agendar Visita</h4>
                    </div>
                    
</div>

<div class="row"  style="padding: 0">
    <div class="col">
            {{ form.errors }}   

            <div class="p-t-0" >
				<div class=" b-all shadow-none">

                    <form method="post" class="form-horizontal">
                    {% csrf_token %}
                  
                    <div class="form-body">
                  
                        <div class="row" style="margin-bottom:20px;"><!--Col row master-->
                                <div class="col-md-12 col-sm-12 "> <!--Col izq-->
                                    <div class="card" style="    height: 100%;">
                                            <div class="card-body">
                                <!--titulo
                                    <div class="row">
                                        <div class="col-md-12">
                                            <h3 class="box-title">Items a evaluar</h3>
                                        </div>
                                    </div>
                                    <hr>
                                 titulo-->

                                     
                                            <div class="row p-t-20 m-l-10">
                                                <div class="col-md-12">

                                                    <div class="form-group row"> 
                                                        <label class="col-10 col-form-label" for="date_time_programmed2">{{form.date_time_programmed.label}}</label>
                                                        <input class="form-control bootstrapMaterialDatePicker" id="date_time_programmed2" name="date_time_programmed" autocomplete="off"  type="text">
                                                       
                                                    </div>

                                                </div><!--col-->
                                            </div> <!--p-t-20-->
                                    
                                     
                                            <div class="row p-t-20 m-l-10">
                                                    <div class="col-md-12">
    
                                                        <div class="form-group row">
                                                            <label class="col-10 col-form-label" for="store">{{form.store.label}}</label>
                                                            {{form.store|add_class:"form-control"|add_class:"p-0"|attr:"autocomplete:off"}}
                                                        </div>
    
                                                    </div><!--col-->
                                                </div> <!--p-t-20-->

                                    </div> <!--CARD BODY-->
                                </div> <!--CARD-->
                                </div> <!--Col izq-->

                              

                        </div>  <!--Col row master-->

                        <div class="row"><!--Col row master-->
                            <div class="col-12 "> <!--Col izq-->
                                <div class="card">
                                        <div class="card-body">

                                                <div class="row">
                                                        <div class="col-md-12">
                                                                <button class="btn btn-primary waves-effect waves-light  m-r-10" type="submit">GUARDAR</button>

                                                                <a href="{% url 'audits' %}">
                                                                    <button class="btn btn-inverse waves-effect waves-light" type="button">CANCELAR</button>
                                                                </a>
                                                        </div>
                                                    </div>

                                        </div> <!--Card Body-->  
                                </div>         <!--Card-->   
                            </div>   <!--Col submitsq-->  
                        </div><!--Col row master-->


                    </div><!--form-body-->
                    </form>

                </div><!--Content-->
            </div><!--Content-->    


    </div><!---->
</div><!--Row-->

<div id="overlayGeo">
    <div id="textOver">Es necesario conocer tu ubicación actual.</div>
</div>
<div id="status"></div>

</div><!--col 12-->
</div><!--row-->
</div><!--container fluid-->


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel1" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                
                <div class="modal-body">
                    <img id="bigimage" class="img-fluid" src="">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
</div>


{% endblock %}

{% block contentContainer %}

{% endblock %}

{% block javascript %}
    <script>
        
    $('#date_time_programmed2').bootstrapMaterialDatePicker({ format: 'YYYY/MM/DD HH:mm' });
  /*      jQuery('[name="date_time_programmed"]').datetimepicker();
    $(document).ready(function(){
        jQuery('#id_store option:first').text("");
    });*/
    </script>
{% endblock %}

templates/auditor/user.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Mi perfil{% endblock %}

{% block content %}
    
    <h2> User </h2>

        <div class="row">

                            <div class="col-lg-4 col-xlg-3 col-md-5">
                                <div class="card">
                                    <div class="card-body">
                                        <center class="m-t-30"> <img src="/{{ object.avatar }}" class="img-circle" width="150" />
                                            <h4 class="card-title m-t-10">{{ object.first_name }}</h4>
                                            <h6 class="card-subtitle">{{ object.get_profile }}</h6>
                                        </center>
                                    </div>
                                    <div class="card-body"> 
                                        <small class="text-muted">Correo </small>
                                        <h6>{{ object.email }}</h6> 
                                        <small class="text-muted p-t-30 db">Teléfono</small>
                                        <h6>{{ object.mobile }}</h6> 
                                        <small class="text-muted p-t-30 db">Último ingreso</small> 
                                        <h6>{{ object.last_login }}</h6>                              
                                        <br/>
                                    </div>
                                </div>
                            </div>

                            <div class="col-lg-8 col-xlg-9 col-md-7">
                                <div class="card">

                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <!-- tab-->
                                        <div>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-3 col-xs-6 b-r"> <strong>Full Name</strong>
                                                        <br>
                                                        <p class="text-muted">{{object.get_fullname }}</p>
                                                    </div>
                                                    <div class="col-md-3 col-xs-6 b-r"> <strong>Mobile</strong>
                                                        <br>
                                                        <p class="text-muted">{{ object.mobile }}</p>
                                                    </div>
                                                    <div class="col-md-3 col-xs-6 b-r"> <strong>Email</strong>
                                                        <br>
                                                        <p class="text-muted">{{ object.email }}</p>
                                                    </div>
                                                    <div class="col-md-3 col-xs-6"> <strong>User</strong>
                                                        <br>
                                                        <p class="text-muted">{{ object.username }}</p>
                                                    </div>
                                                </div>
                                                <hr>
                                                <h4 class="font-medium m-t-30">Statistics</h4>
                                                <hr>
                                                    <center>Coming Soon</center> 
                                            </div>
                                        </div>
    
                                    </div>
                                </div>
                            </div>
                            <!-- Column -->
            </div>


{% endblock %}

{% block javascript %}
<script src="/static/assets/js/pages/jasny-bootstrap.js"></script>
<script src="/static/assets/node_modules/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
<script>
$(document).ready(function(){
        $("input").addClass("form-control");
        $("select").addClass("form-control");
        $("textarea").addClass("form-control");
        $("select").select2();
        document.getElementsByTagName("form")[0].setAttribute("enctype", "multipart/form-data");
});
</script>
{% endblock %}