task/urls.py
"""
task URL Configuration
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app import views
from rest_framework import routers

# routers API REST
router = routers.DefaultRouter()
router.register(r'task-form-field', views.TaskFormFieldsViewSet)


urlpatterns = [
    re_path(r'^', include('user_profile.urls')),
    re_path(r'^', include('messages.urls')),
    re_path(r'^', include('store.urls')),
    re_path(r'^', include('project.urls')),
    re_path(r'^', include('audits.urls')),
    # Administrador
    path('administrator/', admin.site.urls),
    path('administrator/doc/', include('django.contrib.admindocs.urls')),
    # Dashboard
    path('', views.dashboard, name='dashboard'),
    # Auditor
    re_path(
        r'update-rating-task/(?P<pk>\d+)/$',
        views.UpdateRatingTaskView.as_view(),
        name='update-rating-task',
    ),
    re_path(
        r'new-rate-task/(?P<pk>\d+)/$',
        views.CreateRatingTaskView.as_view(),
        name='create-rating-task',
    ),
    # Operator
    path(
        'calendar-operator',
        views.calendar_operator,
        name='calendar-operator'
    ),
    re_path(
        r'task-execute-new-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorNew.as_view(),
        name='task-execute-doc-new'
    ),
    re_path(
        r'task-execute-update-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorUpdate.as_view(),
        name='task-execute-doc-update'
    ),
    re_path(
        r'task-administrator-remove/(?P<pk>\d+)/$',
        views.TaskDelete.as_view(),
        name='task-delete'
    ),
    re_path(
        r'task-execute-new-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorNew.as_view(),
        name='task-execute-form-new'
    ),
    re_path(
        r'task-execute-update-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorUpdate.as_view(),
        name='task-execute-form-update'
    ),
    # Administrador
    path(
        'reports-administrator/',
        views.reports_administrator,
        name='reports_administrator'
    ),
    path(
        'help-administrator/',
        views.Help.as_view(),
        name='help-administrator'
    ),
    path(
        'help-operator/',
        views.HelpOperator.as_view(),
        name='help-operator'
    ),
    re_path(
        r'task-administrator/',
        views.task_administrator,
        name='task_administrator'
    ),
    re_path(
        r'assign-task/(?P<pk>\d+)/$',
        views.AssignTask.as_view(),
        name='task_assign'
    ),
    re_path(
        r'task-administrator-update/(?P<pk>\d+)/$',
        views.TaskAdministratorUpdateDoc.as_view(),
        name='task_administrator_update_document'
    ),
    re_path(
        r'task-administrator-update-modal',
        views.TaskAdministratorUpdateDocModal.as_view(),
        name='task_administrator_update_document_modal'
    ),
    re_path(
        r'task-administrator-new-document/',
        views.TaskAdministratorNewDoc.as_view(),
        name='task_administrator_new_document'
    ),
    re_path(r'^task-execute/(?P<store_id>\d+|)/(?P<task_id>\d+|)/(?P<project_id>\d+|)', views.StoreTaskExecute.as_view()),
    path('task-upload-evidence/', views.upload_task_evidence),
    path('task-audit/<int:result_id>', views.TaskAudit.as_view()),
    path('login/', auth_views.login, {'template_name': 'site/login.html'}),
    path('/', auth_views.login, {'template_name': 'site/login.html'}),
    path('forgot-password/', auth_views.password_reset, {'template_name': 'site/forgot_password.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, {'template_name': 'site/password_reset_done.html'}, name='password_reset_done'),
    path('logout/', views.log_out, name='logout'),
    # API REST
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/models.py
from django.contrib.gis.db import models
from functools import reduce
from datetime import datetime, date
from django.core.exceptions import ObjectDoesNotExist
from django.template import RequestContext
from task.middlewares import RequestMiddleware
from datetime import datetime

TASK_TYPE_CHOICES = (
    ('document', 'Foto / Documento'),
    ('form', 'Formulario / Encuesta'),
)

TASK_PERIODICITY_CHOICES = (
    ('Daily', 'Diario'),
    ('Monthly', 'Mensual'),
    ('Unique', 'Único'),
)

TASK_DAY_NUMBER_CHOICES = (
    ('01', '01'),
    ('02', '02'),
    ('03', '03'),
    ('04', '04'),
    ('05', '05'),
    ('06', '06'),
    ('07', '07'),
    ('08', '08'),
    ('09', '09'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('18', '18'),
    ('19', '19'),
    ('20', '20'),
    ('21', '21'),
    ('22', '22'),
    ('23', '23'),
    ('24', '24'),
    ('25', '25'),
    ('26', '26'),
    ('27', '27'),
    ('28', '28'),
    ('29', '29'),
    ('30', '30'),
    ('31', '31'),
    ('End of the month', 'End of the month'),
)

FORM_TYPE_CHOICES = (
    ('checkbox', 'Checkbox'),
    ('number', 'Número'),
    ('textarea', 'Texto largo'),
    ('radio', 'Selección múltiple'),
)

FORM_CLASS_CHOICES = (
    ('form-control', 'Normal'),
)

TASK_FORM_INPUT_TYPES = (
    ('open-ended-question', 'Open ended question'),
    ('multiple-choice', 'Multiple choise'),
    ('checkbox', 'checkbox'),
    ('number', 'number'),
)


class TaskStore(models.Model):
    store = models.ForeignKey('store.Store', on_delete=models.CASCADE)
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    

class Task(models.Model):
    """ Model task """
    name = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        default=None,
        verbose_name="Nombre"
    )
    owner = models.ForeignKey(
        'user_profile.User',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Creado por"
    )
    periodicity = models.CharField(
        max_length=30,
        choices=TASK_PERIODICITY_CHOICES,
        verbose_name="Periodicidad"
    )
    type = models.CharField(max_length=30, choices=TASK_TYPE_CHOICES, verbose_name="Tipo de tarea",)
    # aplica para todos los tipo de periodicidad
    start_date = models.DateField(
        blank=True,
        null=True,
        verbose_name="Fecha de inicio"
    )
    end_date = models.DateField(
        blank=True,
        null=True,
        verbose_name="Fecha de finalización"
    )
    start_hour = models.TimeField(
        null=True,
        blank=True,
        default=None,
        verbose_name="Hora de inicio"
    )
    end_hour = models.TimeField(
        null=True,
        blank=True,
        default=None,
        verbose_name="Hora de finalización"
    )
    # Dias de la semana en la que se ejecuta una tarea empieza en lunes=0 y
    # esta separada por ","
    days = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default="0,1,2,3,4,5,6",
        verbose_name="Días"
    )
    week = models.CharField(
        max_length=50,
        null=True,
        blank=True,
        default="0,1,2,3",
        verbose_name="Semana"
    )
    # datos para tipo Monthly
    day_number = models.CharField(
        max_length=30,
        choices=TASK_DAY_NUMBER_CHOICES,
        null=True,
        verbose_name="Día",
        blank=True
    )
    active = models.BooleanField(
        default=True
    )
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="Ejecutar después de",
        blank=True,
        related_name='ta_task'
    )
    store = models.ManyToManyField(
        'store.Store',
        null=True,
        blank=True,
        verbose_name="Tienda",
        related_name='tasks'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    instructions = models.TextField(blank=True, verbose_name="Instrucciones",)
    is_audit = models.BooleanField(default=False)
    
    def get_periodicity(self):
        return dict(TASK_PERIODICITY_CHOICES)[self.periodicity]
    
    def get_type(self):
        return dict(TASK_TYPE_CHOICES)[self.type] 
    
    def verbose_type(self):
        return dict(TASK_TYPE_CHOICES)[self.type] 

    def get_complete_percent(self):
        return '{}%'.format(int((self.get_total_completed_tasks() * 100) / self.get_total_tasks()))

    def get_score(self):
        childrens = self.ta_task.all()
        completed_tasks = 0
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request

        for children in childrens:
            if (children.is_complete(request)):
                completed_tasks += 1

        if completed_tasks == 0:
            return 0
        completed = int((completed_tasks * 100) / childrens.count())
        return '{}%'.format(completed)

    def projects_names(self):
        names = []
        return reduce(
            lambda prev, ta: "{}, {}".format(prev, ta.project.name) if prev else ta.project.name, 
            self.assignment.all(),
            ''
        )

    def get_duration(self):
        return (
            datetime.combine(date.today(), self.end_hour) -
            datetime.combine(date.today(), self.start_hour)
        )

    def get_instructions(self):
        if len(self.instructions) > 50:
            return self.instructions[:50] + "..."
        else:
            return self.instructions[:50]

    def is_complete(self):
        request = RequestMiddleware(get_response=None)
        request = request.thread_local.current_request
        return TaskAssignmentResult.objects.filter(
            task=self,
            store__manager=request.user
        ).exists()

    def get_total_tasks(self, count=1):
        if not self.ta_task:
            return count
        return reduce((lambda x, y: x + y.get_total_tasks()), self.ta_task.all(), count)

    def get_total_completed_tasks(self, count=None):
        if not self.ta_task:
            return count
        if count is None:
            count = 1 if self.is_complete() else 0

        return reduce(
            (lambda x, y: x + y.get_total_completed_tasks()),
            self.ta_task.all(),
            count
        )

    def get_progress(self):
        completed = self.get_total_completed_tasks()
        if (completed == 0):
            return 0
        total_tasks = self.get_total_tasks()

        return int((completed * 100) / total_tasks)

    class Meta:
        db_table = 'task'

    def __str__(self):
        return self.name


class TaskFormFields(models.Model):
    label = models.CharField(max_length=200)
    input_type = models.CharField(
        max_length=200,
        choices=TASK_FORM_INPUT_TYPES
    )
    options = models.TextField(blank=True)
    task = models.ForeignKey(
        to=Task,
        on_delete=models.CASCADE,
        related_name='formFields'
    )
    optional = models.BooleanField(default=False)

    def is_multiple(self):
        return self.input_type == 'multiple-choice'

    def options_array(self):
        return self.options.split(',')


class TaskFormResponse(models.Model):
    assignment_result = models.ForeignKey(
        to='TaskAssignmentResult',
        on_delete=models.CASCADE,
        related_name="form_responses"
    )
    formField = models.ForeignKey(
        to='TaskFormFields',
        on_delete=models.CASCADE
    )
    response = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)


# Asignación de tareas a proyectos
class TaskAssignment(models.Model):
    """ Model Task Form Template: save json form """
    task = models.ForeignKey(
        'Task',
        on_delete=models.CASCADE,
        null=True,
        related_name='assignment'
    )
    project = models.ForeignKey(
        'project.Project',
        on_delete=models.CASCADE,
        null=True,
        related_name='task_assignments'
    )

    class Meta:
        db_table = 'task_assignment'

    def __str__(self):
        try:
            return "%s (%s)" % (self.task.name, self.store.name)
        except(ObjectDoesNotExist, AttributeError):
            return ''

    def is_saved(self, date):
        try:
            r = TaskAssignmentResult.objects.filter(
                #task_assignment=self,
                date__day=date.day,
                date__month=date.month,
                date__year=date.year
            )[:1].get()
            return {'object': r, 'status': True}
        except TaskAssignmentResult.DoesNotExist:
            return {'object': None, 'status': False}
    
    def next_task_assignment(self):
        next_assignment = TaskAssignment.objects.filter(
            task__seguimiento__tarea_completada=0,
            project=self.project,
            task__parent=self.task,
        ).first()
        if (next_assignment):
            return next_assignment

    def is_auditee(self, date):
        try:
            r = TaskAssignmentResult.objects.filter(
                task_assignment=self,
                date__day=date.day,
                date__month=date.month,
                date__year=date.year
            )[:1].get()
            return {'object': r, 'status': True}
        except TaskAssignmentResult.DoesNotExist:
            return {'object': None, 'status': False}


class SeguimientoTareas(models.Model):
    tarea = models.CharField(max_length=50),
    task = models.ForeignKey(Task, related_name="seguimiento", on_delete=models.DO_NOTHING)
    tarea_completada = models.BooleanField()
    nombre_tienda = models.CharField(max_length=50)

    class Meta:
        db_table = 'seguimiento_tareas'
        managed = False

    def delete(self, *args, **kwargs):
        pass # deletion of a view row is never valid

class AvancesProyectoView(models.Model):

templates/administrator/add_zone_modal.html
<div class="modal" tabindex="-1" role="dialog" id="create_zone_modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title">Crear nueva Zona</h5>
      </div>
        <div class="modal-body">
            <div class="form-group">
                <label for="zone_name">Nombre de la zona:</label>
                <input id="zone_name" type="text" class="form-control" v-model="zone_name" />
            </div>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" @click="save" :disabled="submitting">
            <span v-if="submitting">Enviando...</span>
            <span v-if="!submitting">Guardar</span>
        </button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
      </div>
    </div>
  </div>
</div>

templates/administrator/reports-administrator.html
{% extends 'site/base_dashboard.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
<iframe    src=""    frameborder="0"    width="100%"    height="600"    allowtransparency></iframe>
{% endblock %}
{% block javascript %}
<script src="/static/assets/js/pages/jasny-bootstrap.js"></script>
<script src="/static/assets/node_modules/select2/dist/js/select2.full.min.js" type="text/javascript"></script>
<script src="/static/assets/node_modules/calendar/jquery-ui.min.js"></script>

{% endblock %}

templates/administrator/task-administrator-document-modal.html
{% load widget_tweaks %}

{% block css %}
<style type="text/css">
.select2-selection__choice {
     color: #fff !important;
     background-color: #009efb !important;
}

.select2-selection__choice__remove {
     color: #fff !important;
     background-color: #009efb !important;
}
</style>
{% endblock %}

{% block contentContainer %}
{{ form.errors  }}
<div id="vue-app">
	<div class="card">
		<div class="card-body">
	<ul class="nav nav-tabs customtab" role="tablist">
	{% if not is_audit %}
		<li class="nav-item"> <a class="nav-link {% if 'Daily' == form.periodicity.value  %} active {% endif %}" data-toggle="tab" href="#navpills-1" role="tab" aria-selected="true"><span><span>Diaria</span></a> </li>
		<li class="nav-item"> <a class="nav-link {% if 'Monthly' == form.periodicity.value  %} active {% endif %}" data-toggle="tab" href="#navpills-2" role="tab" aria-selected="false"><span><span >Mensual</span></a> </li>
		<li class="nav-item"> <a class="nav-link {% if 'Unique' == form.periodicity.value  %} active {% endif %}" data-toggle="tab" href="#navpills-3" role="tab" aria-selected="false"><span><span >Única</span></a> </li>
	{% endif %}
	</ul>
		<div>
			<div>
			<div class="tab-content br-n pn">
				{% include "administrator/task-administrator-tab1.html" %}
				{% include "administrator/task-administrator-tab2.html" %}
				{% include "administrator/task-administrator-tab3.html" %}
			</div>
			</div>
		</div>
		</div>
	</div>
</div>
</div>
{% endblock %}
{% block javascript %}
<script src="/static/assets/node_modules/tinymce/tinymce.min.js"></script>
<script>
	var start_hour = '{{form.start_hour.value}}';
    var end_hour = '{{form.end_hour.value}}';
    var task_type = '{% if is_audit %}form{% else %}{{ form.type.value }}{% endif %}';
    try {
        var addedQuestions = JSON.parse('{{fields|safe}}');
    } catch(ex) {
        var addedQuestions = [];
    }
</script>
<script src="/static/assets/js/vue-components.js"></script>
<script type="text/javascript">
	function loadJqueryPlugins() {
		setTimeout(function() {
			$(document).ready(function() {
				$('.js-example-basic-multiple').select2();
			});
			$('.bootstrapMaterialDatePicker').bootstrapMaterialDatePicker({ weekStart: 0, time: false });
			$('.timepicker').bootstrapMaterialDatePicker({ format: 'HH:mm', time: true, date: false, okText: 'Establecer', clearText: 'Limpiar', cancelText: 'Cancelar' });
    	    
			if ($("#id_instructions").length > 0) {
				tinymce.init({
					selector: "[name='instructions']",
					theme: "modern",
					height: 100,
					menubar: false,
					plugins: [
					"advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
					"searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
					"save table contextmenu directionality emoticons template paste textcolor"
					],
					toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | preview media fullpage | forecolor backcolor emoticons",
				});
			};
		}, 200)
	}
    $(document).ready(function() {
		$(document).on('shown.bs.tab', 'a[data-toggle="tab"]', function (e) {
			loadJqueryPlugins();
		});
		
		loadJqueryPlugins();
		// Implementation vue-components.js
		createTaskRegisterApp(function(ev) {
			ev.preventDefault();
			$.post('/task-administrator-update-modal', $('.tab-pane.active form').serialize())
				.then(function(res) {
					$('#modal-add-task').modal('toggle');
					$('#multiselect').append('<option value="' + res.id + '">' + res.name + '</option>')
					$('#multiselect').multiSelect('refresh');
				})
				.catch(function() {
					alert("Error creando");
				});
		});
	});
</script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
{% endblock %}

templates/administrator/task-administrator-tab1.html
{% load widget_tweaks %}
<div id="navpills-1" class="tab-pane  {% if 'Daily' == form.periodicity.value  %} active {% endif %}" >
			
        <form method="post" class="form-horizontal m-t-40">
                <h3 class="box-title" style="margin-bottom: 15px">Preferencias de tarea</h3>
                <input hidden name="periodicity" value="Daily" />
        <div class="form-group m-t-40 row">
            <label for="{{form.name.label}}" class="col-12 col-md-2 col-form-label">{{form.name.label}}</label>
            <div class="col-12 col-md-10">
                {{ form.name|add_class:"form-control" }}
            </div>
            {% if form.name.errors %}
            <div style="color: danger">
                {{ form.name.error }}
            </div>
             {% endif %}
        </div>

        {% comment %} <div class="form-group m-t-40 row">
            <label for="{{form.project.label}}" class="col-12 col-md-2 col-form-label">{{form.project.label}}</label>
            <div class="col-12 col-md-10">
                {{ form.project|add_class:"form-control" }}
            </div>
            {% if form.project.errors %}
            <div style="color: danger">
                {{ form.project.error }}
            </div>
             {% endif %}
        </div> {% endcomment %}

        {% if parent_task.count > 0 %}
            <div class="form-group m-t-40 row">
                <label for="{{form.parent.label}}" class="col-12 col-md-2 col-form-label">{{form.parent.label}}</label>
                <div class="col-12 col-md-10">
                    <select name="parent" id="id_parent" class="js-states form-control">
                        <option value="">---------</option>
                        {% for t in parent_task %}
                            <option value="{{t.id}}"  {% if t.id == form.parent.value %} selected {% endif %}>{{t.name}}  </option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.parent.errors %}
                <div style="color: danger">
                    {{ form.parent.error }}
                </div>
                {% endif %}
            </div>
        {% endif %}

        <div class="form-group m-t-40 row">
            <label for="{{form.days.label}}" class="col-12 col-md-2 col-form-label">{{form.days.label}}</label>
            <div class="col-12 col-md-10">
            <select name="days" multiple class="form-control js-example-basic-multiple">
              <option value="0"   {% if '0' in form.days.value  %} selected {% endif %}>Lunes</option>
              <option value="1"   {% if '1' in form.days.value  %} selected {% endif %}>Martes</option>
              <option value="2"   {% if '2' in form.days.value  %} selected {% endif %}>Miercoles</option>
              <option value="3"   {% if '3' in form.days.value  %} selected {% endif %}>Jueves</option>
              <option value="4"   {% if '4' in form.days.value  %} selected {% endif %}>Viernes</option>
              <option value="5"   {% if '5' in form.days.value  %} selected {% endif %}>Sabado</option>
              <option value="6"   {% if '6' in form.days.value  %} selected {% endif %}>Domingo</option>
            </select>
            </div>
            {% if form.days.errors %}
            <div class="invalid-feedback">
                {{ form.days.error }}
            </div>
             {% endif %}
        </div>
        <div class="form-group row">
            <label for="{{form.start_hour.label}}" class="col-12 col-md-2 col-form-label">{{form.start_hour.label}}</label>
            <div class="col-12 col-md-4">
                <div class="input-group clockpicker " data-placement="left" data-align="top" data-autoclose="true">
                    <input v-bind:value="start_hour" type="text" name="start_hour" id="id_start_hour" placeholder="hh:mm" class="form-control timepicker" >
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-clock-o"></i></span>
                        </div>
                </div>
            </div>
            {% if form.start_hour.errors %}
            <div class="invalid-feedback">
                {{ form.start_hour.errors }}
            </div>
             {% endif %}

            <label for="{{form.end_hour.label}}" class="col-12 col-md-2 col-form-label">{{form.end_hour.label}}</label>
            <div class="col-12 col-md-4">
                <div class="input-group clockpicker " data-placement="left" data-align="top" data-autoclose="true">
                    <input v-bind:value="end_hour" type="text" name="end_hour" id="id_end_hour" placeholder="hh:mm" class="form-control timepicker"  >
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-clock-o"></i></span>
                        </div>
                </div>
            </div>
            {% if form.end_hour.errors %}
            <div class="invalid-feedback">
                {{ form.end_hour.error }}
            </div>
             {% endif %}
        </div>
        {% include "administrator/task-administration-tab-commons.html"%}
        </form>


    </div>

templates/administrator/task-administrator-tab2.html
{% load widget_tweaks %}
<div id="navpills-2" class="tab-pane  {% if 'Monthly' == form.periodicity.value  %} active {% endif %}">
        <form method="post" class="form-horizontal m-t-40">
            <input hidden name="periodicity" value="Monthly" />
        <div class="form-group m-t-40 row">
            <label for="{{form.name.label}}" class="col-12 col-md-2 col-form-label">{{form.name.label}}</label>
            <div class="col-12 col-md-10">
                {{ form.name|attr:"placeholder:Name"|add_class:"form-control" }}
            </div>
            {% if form.name.errors %}
            <div style="color: danger">
                {{ form.name.error }}
            </div>
             {% endif %}
        </div>
        {% if parent_task.count > 0 %}
            <div class="form-group m-t-40 row">
                <label for="{{form.parent.label}}" class="col-12 col-md-2 col-form-label">{{form.parent.label}}</label>
                <div class="col-12 col-md-10">
                    <select name="parent" id="id_parent" class="js-states form-control">
                        <option value="">---------</option>
                        {% for t in parent_task %}
                            <option value="{{t.id}}"  {% if t.id == form.parent.value %} selected {% endif %}>{{t.name}}  </option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.parent.errors %}
                <div style="color: danger">
                    {{ form.parent.error }}
                </div>
                {% endif %}
            </div>
        {% endif %}

        <div class="form-group m-t-40 row">
            <label for="{{form.days.label}}" class="col-12 col-md-2 col-form-label">{{form.days.label}}</label>
            <div class="col-12 col-md-10">
            <select name="days" multiple class="form-control js-example-basic-multiple">
              <option value="0"   {% if '0' in form.days.value  %} selected {% endif %}>Lunes</option>
              <option value="1"   {% if '1' in form.days.value  %} selected {% endif %}>Martes</option>
              <option value="2"   {% if '2' in form.days.value  %} selected {% endif %}>Miercoles</option>
              <option value="3"   {% if '3' in form.days.value  %} selected {% endif %}>Jueves</option>
              <option value="4"   {% if '4' in form.days.value  %} selected {% endif %}>Viernes</option>
              <option value="5"   {% if '5' in form.days.value  %} selected {% endif %}>Sabado</option>
              <option value="6"   {% if '6' in form.days.value  %} selected {% endif %}>Domingo</option>
            </select>
            </div>
            {% if form.days.errors %}
            <div class="invalid-feedback">
                {{ form.days.error }}
            </div>
             {% endif %}
        </div>


        <div class="form-group m-t-40 row">
            <label for="{{form.week.label}}" class="col-12 col-md-2 col-form-label">{{form.week.label}}</label>
            <div class="col-12 col-md-10">
            <select name="week" multiple class="form-control js-example-basic-multiple">
              <option value="0"  {% if '0' in form.week.value  %} selected {% endif %}>Week 1</option>
              <option value="1"  {% if '1' in form.week.value  %} selected {% endif %}>Week 2</option>
              <option value="2"  {% if '2' in form.week.value  %} selected {% endif %}>Week 3</option>
              <option value="3"  {% if '3' in form.week.value  %} selected {% endif %}>Week 4</option>
            </select>
            </div>
            {% if form.week.errors %}
            <div class="invalid-feedback">
                {{ form.week.error }}
            </div>
             {% endif %}
        </div>



        <div class="form-group m-t-40 row">
            <label for="{{form.day_number.label}}" class="col-12 col-md-2 col-form-label">{{form.day_number.label}}</label>
            <div class="col-12 col-md-10">
                {{ form.day_number|add_class:"form-control" }}
            </div>
            {% if form.day_number.errors %}
            <div style="color: danger">
                {{ form.day_number.error }}
            </div>
             {% endif %}
        </div>


        <div class="form-group row">
            <label for="{{form.start_hour.label}}" class="col-12 col-md-2 col-form-label">{{form.start_hour.label}}</label>
            <div class="col-12 col-md-4">
                <div class="input-group clockpicker " data-placement="left" data-align="top" data-autoclose="true">
                    <input v-bind:value="start_hour" type="text" name="start_hour" id="id_start_hour" placeholder="hh:mm" class="form-control timepicker" >
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-clock-o"></i></span>
                        </div>
                </div>
            </div>
            {% if form.start_hour.errors %}
            <div class="invalid-feedback">
                {{ form.start_hour.errors }}
            </div>
             {% endif %}

            <label for="{{form.end_hour.label}}" class="col-12 col-md-2 col-form-label">{{form.end_hour.label}}</label>
            <div class="col-12 col-md-4">
                <div class="input-group clockpicker " data-placement="left" data-align="top" data-autoclose="true">
                    <input v-bind:value="end_hour" type="text" name="end_hour" id="id_end_hour" placeholder="hh:mm" class="form-control timepicker"  >
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-clock-o"></i></span>
                        </div>
                </div>
            </div>
            {% if form.end_hour.errors %}
            <div class="invalid-feedback">
                {{ form.end_hour.error }}
            </div>
             {% endif %}
        </div>
        {% include "administrator/task-administration-tab-commons.html"%}
        </form>

    </div>