task/urls.py
"""
task URL Configuration
"""
from django.contrib import admin
from django.urls import path
from django.conf.urls import re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from app import views
from rest_framework import routers

# routers API REST
router = routers.DefaultRouter()
router.register(r'task-form-field', views.TaskFormFieldsViewSet)


urlpatterns = [
    re_path(r'^', include('user_profile.urls')),
    re_path(r'^', include('messages.urls')),
    re_path(r'^', include('store.urls')),
    re_path(r'^', include('project.urls')),
    re_path(r'^', include('audits.urls')),
    # Administrador
    path('administrator/', admin.site.urls),
    path('administrator/doc/', include('django.contrib.admindocs.urls')),
    # Dashboard
    path('', views.dashboard, name='dashboard'),
    # Auditor
    re_path(
        r'update-rating-task/(?P<pk>\d+)/$',
        views.UpdateRatingTaskView.as_view(),
        name='update-rating-task',
    ),
    re_path(
        r'new-rate-task/(?P<pk>\d+)/$',
        views.CreateRatingTaskView.as_view(),
        name='create-rating-task',
    ),
    # Operator
    path(
        'calendar-operator',
        views.calendar_operator,
        name='calendar-operator'
    ),
    re_path(
        r'task-execute-new-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorNew.as_view(),
        name='task-execute-doc-new'
    ),
    re_path(
        r'task-execute-update-document/(?P<pk>\d+)/$',
        views.TaskExecuteDocOperatorUpdate.as_view(),
        name='task-execute-doc-update'
    ),
    re_path(
        r'task-administrator-remove/(?P<pk>\d+)/$',
        views.TaskDelete.as_view(),
        name='task-delete'
    ),
    re_path(
        r'task-execute-new-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorNew.as_view(),
        name='task-execute-form-new'
    ),
    re_path(
        r'task-execute-update-form/(?P<pk>\d+)/$',
        views.TaskExecuteFormOperatorUpdate.as_view(),
        name='task-execute-form-update'
    ),
    # Administrador
    path(
        'reports-administrator/',
        views.reports_administrator,
        name='reports_administrator'
    ),
    path(
        'help-administrator/',
        views.Help.as_view(),
        name='help-administrator'
    ),
    path(
        'help-operator/',
        views.HelpOperator.as_view(),
        name='help-operator'
    ),
    re_path(
        r'task-administrator/',
        views.task_administrator,
        name='task_administrator'
    ),
    re_path(
        r'assign-task/(?P<pk>\d+)/$',
        views.AssignTask.as_view(),
        name='task_assign'
    ),
    re_path(
        r'task-administrator-update/(?P<pk>\d+)/$',
        views.TaskAdministratorUpdateDoc.as_view(),
        name='task_administrator_update_document'
    ),
    re_path(
        r'task-administrator-update-modal',
        views.TaskAdministratorUpdateDocModal.as_view(),
        name='task_administrator_update_document_modal'
    ),
    re_path(
        r'task-administrator-new-document/',
        views.TaskAdministratorNewDoc.as_view(),
        name='task_administrator_new_document'
    ),
    re_path(r'^task-execute/(?P<store_id>\d+|)/(?P<task_id>\d+|)/(?P<project_id>\d+|)', views.StoreTaskExecute.as_view()),
    path('task-upload-evidence/', views.upload_task_evidence),
    path('task-audit/<int:result_id>', views.TaskAudit.as_view()),
    path('login/', auth_views.login, {'template_name': 'site/login.html'}),
    path('/', auth_views.login, {'template_name': 'site/login.html'}),
    path('forgot-password/', auth_views.password_reset, {'template_name': 'site/forgot_password.html'}, name='password_reset'),
    path('password_reset/done/', auth_views.password_reset_done, {'template_name': 'site/password_reset_done.html'}, name='password_reset_done'),
    path('logout/', views.log_out, name='logout'),
    # API REST
    re_path(r'^', include(router.urls)),
    re_path(r'^api-auth/', include(
        'rest_framework.urls', namespace='rest_framework')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/models.py
from django.contrib.gis.db import models

"""
Atributos choice para los campos
"""
LOCATION_TYPE_CHOICES = (
    ('Country', 'Country'),
    ('Province', 'Province'),
    ('City', 'City'),
    ('Zone', 'Zona'),
)


class Location(models.Model):
    """ Model location (longitude y latitude) """
    name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        default=None
    )
    type = models.CharField(max_length=20, choices=LOCATION_TYPE_CHOICES)
    parent = models.ForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='lo_location'
    )
    longitude = models.DecimalField(max_digits=8, decimal_places=6, default=0)
    latitude = models.DecimalField(max_digits=8, decimal_places=6, default=0)
    iso = models.CharField(
        max_length=3,
        null=True,
        blank=True,
        default=None,
        verbose_name="ISO"
    )

    class Meta:
        db_table = 'location'

    def __str__(self):
        if self.parent is None:
            return "%s" % (self.name)
        else:
            return "%s (%s)" % (
                self.name,
                self.parent.name
            )


# Create your models here.
class Store(models.Model):
    """ Model store """
    name = models.CharField(
        max_length=50,
        null=False,
        blank=False,
        default=None,
        verbose_name="Nombre"
    )
    image = models.ImageField(
        upload_to='static/files/store/',
        default='static/files/store/no-image.jpg',
        verbose_name="Fotografía",
        blank=True,
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
        verbose_name="País",
        related_name="country"
    )
    zone = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        default=None,
        verbose_name="Zona",
        related_name="zone"
    )
    addres = models.CharField(
        max_length=100,
        null=False,
        default=None,
        verbose_name="Dirección"
    )
    active = models.BooleanField(default=True, verbose_name="Habilitada")
    manager = models.ForeignKey(
        'user_profile.User',
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name='manager',
        verbose_name="Gerente"
    )
    auditor = models.ForeignKey(
        'user_profile.User',
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        related_name='auditor',
        verbose_name="Director Regional"
    )
    phone = models.CharField(
        max_length=16,
        null=True,
        blank=True,
        default=None,
        verbose_name="Teléfono"
    )
    email = models.EmailField(
        verbose_name="Correo de la tienda"
    )
    coords = models.PointField(null=True, blank=True, verbose_name="Coordenadas")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'store'

    def __str__(self):
        return self.name
    

user_profile/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from messages.models import Message
from django.utils import timezone


CLIENT_THEME_CHOICES = (
    ('skin-default', 'Gray'),
    ('skin-green', 'Green'),
    ('skin-red', 'Red'),
    ('skin-blue', 'Blue'),
    ('skin-purple', 'Purple'),
    ('skin-megna', 'Megna'),
    ('skin-default-dark', 'Gray Dark'),
    ('skin-green-dark', 'Green Dark'),
    ('skin-red-dark', 'Red Dark'),
    ('skin-blue-dark', 'Blue Dark'),
    ('skin-purple-dark', 'Purple Dark'),
    ('skin-megna-dark', 'Megna Dark'),
)

"""
Modelos
""" 
class Client(models.Model):
    """
    Model Client for contact, info and app configuration  
    """
    name = models.CharField(max_length=100,null=False,blank=False,default=None,verbose_name="Name")
    logo = models.ImageField(blank=True, upload_to='static/files/logo/', default='static/files/logo/no-image.png')
    theme  = models.CharField(max_length=20, choices=CLIENT_THEME_CHOICES, default='skin-default')

    class Meta:
        db_table = 'client'

    def __str__(self):
        return self.name


class User(AbstractUser):
    """Custom User model """
    email = models.EmailField('Correo', unique=True)
    mobile = models.CharField(max_length=16,null=True,blank=True,default=None, verbose_name="Teléfono")
    avatar = models.ImageField(blank=True, upload_to='static/files/avatar/', default='static/files/avatar/no-image.png', verbose_name="Foto")
    client = models.ForeignKey(Client, on_delete=models.CASCADE,blank=True,null=True,default=None, verbose_name="Empresa")

    def get_fullname(self):
        """ retun user fullname  """
        return "%s %s" % (self.first_name,self.last_name)

    def get_profile(self):
        """ retun user fullname  """
        p = self.groups.values_list('name',flat=True).first()
        return p

    def get_messages_new(self):
        """ retun user fullname  """
        messages = Message.objects.filter(to_user=self,read=False)
        def count(self):
            return len(messages)
        return messages

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.get_fullname()

    def __unicode__(self):
        return self.get_fullname()

templates/user/create_user.html
{% extends "site/base_dashboard.html" %}
{% load widget_tweaks %}
{% load task_extras %}
{% block css %}
  <link rel="stylesheet" href="/static/assets/node_modules/dropify/dist/css/dropify.min.css" />
{% endblock css %}
{% block contentContainer %}  
<div>
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h4 class="text-themecolor">Crear Usuario</h4>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            {% if form.errors %}
                <div class="alert alert-danger">
                    {{form.errors}}
                </div>
            {% endif %}
            <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                    <label class="col-md-2 col-form-label" for="id_avatar">{{form.avatar.label}}</label>
                    <div class="col-12 col-md-4">
                        {% with 'data-default-file:/'|concat_string:form.avatar.value as default_avatar %}
                            {{ form.avatar|add_class:"dropify"|attr:'placeholder:Imagen'|attr:default_avatar }}
                        {% endwith %}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_first_name">{{form.first_name.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.first_name|add_class:"form-control"|attr:'placeholder:Nombres:'}}
                    </div>
                </div>
                
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_last_name">{{form.last_name.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.last_name|add_class:"form-control"|attr:'placeholder:Apellidos:'}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_email">{{form.email.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.email|add_class:"form-control"|attr:'placeholder:Correo'}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_mobile">{{form.mobile.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.mobile|add_class:"form-control"|attr:'placeholder:Teléfono'}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_username">{{form.username.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.username|add_class:"form-control"|attr:'placeholder:Usuario:'}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_password">{{form.password.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.password|add_class:"form-control"|attr:'placeholder:Contraseña:'|attr:"type:password"}}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-12 col-md-2 col-form-label" for="id_groups">{{form.groups.label}}</label>
                    <div class="col-12 col-md-10">
                        {{form.groups|add_class:"form-control"|attr:'placeholder:rol:'}}
                    </div>
                </div>
                <button class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>
</div>
{% endblock contentContainer %}
{% block javascript %}
<script src="/static/assets/node_modules/dropify/dist/js/dropify.min.js"></script>
<script>
    $(function() {
        $('.dropify').dropify({
            messages: {
                default: 'Subir fotografía',
                replace: 'Replazar',
                remove: 'Remover',
                error: 'Error procesando la imagen'
            }
        });
    })
</script>
{% endblock javascript %}